### ISSUE TITLE
Background-grid doesn't scroll

### ISSUE THREAD

**Issue by morphace** [tltv/gantt#17]
Hi,

I'm using Vaadin 7.4.1 and the latest release of the Gantt add on under OS X.

When you scroll down (you can use the demo) inside Chrome, the grid will not scroll with the Gantt steps.
Inside Safari it works as expected. So there must be an issue with Chrome (41.0.2272.118 (64-bit)).

Thanks,
Markus

**Comment by morphace** [comment]
Same problem on mobile Safari by the way...

**Comment by tltv** [comment]
This is fixed in version 0.9.0.
