### ISSUE TITLE
Show full description of step when small step

### ISSUE THREAD

**Issue by Fluffysandals** [tltv/gantt#19]
For small steps, the "overflow : hidden" property prevents to see the caption properly. Could there be a way to either show a tooltip with a mouse over with the full description, or to choose wether or not the description should be "aligned" with the step size?

**Comment by tltv** [comment]
Step has now description field that is shown as a tooltip if set. Supports also HTML content in the same way as all tooltips in Vaadin components. Checkout latest version from master branch.

**Comment by Fluffysandals** [comment]
Cheers for that!
