### ISSUE TITLE
NullPointerException when retrieving step with getStep(String uid)

### ISSUE THREAD

**Issue by Fluffysandals** [tltv/gantt#20]
With the latest version, I am getting a Nullpointerexception when resizing a step which was added to the gantt. 
The getStep(String Uid) method actually returns a Step which is empty (getcaption, getstartdate etc always return null, even though the step was correctly added).

I have tried this programatically and with the gantt layout, and always gets the problem.

**Comment by tltv** [comment]
I can't reproduce this with 0.9.0 version. Could you please provide some simple test case that reproduces the exception?

**Comment by Fluffysandals** [comment]
Actually, I had subclassed Step to my own needs and linked it to a "task" entity of my persistence layer, which caused the error. Going back to the Step class only, it works well.

**Comment by tltv** [comment]
Alright, case closed then. Make sure than subclass respects super.equals and super.hashCode methods. Otherwise Gantt's internal logic will throw NPE for sure.
