### ISSUE TITLE
Gantt interface not being shown properly

### ISSUE THREAD

**Issue by tltv** [tltv/gantt#21]
"Thank you for this add-on. Probably, I made mistake when I tried to use gantt. I compile widgetset. Add jar to my project classpath. I got no compile and runtime error .But I cannot see interface properly. Thanks in advance"
 -kadireray doganlar @ https://vaadin.com/directory#!addon/gantt

**Comment by tltv** [comment]
Interface not being shown properly may be because of many reasons. 
Check out the demo app sources (https://github.com/tltv/gantt/tree/master/gantt-demo). 
First, make sure that your app inherits gantt addon in your .gwt.xml file. 
Then also make sure that gantt theme is icluded correctly. If you use Valo theme, then just copy the samples in src/main/webapp/VAADIN/themes/demo folder and rename theme name 'demo' to correct one. 
And don't forget @Theme("yourThemeName") in your UI class.

**Comment by kadireray** [comment]
That's what I exactly did. I dont think that there is a problem in implemantation of class. I attached a screenshot when I open the window in which my gantt is implemented. I do not have any idea why it was happened and how to solve this problem.
![gantt](https://cloud.githubusercontent.com/assets/11184729/8253010/02bc7062-1694-11e5-8dec-4f917a161e96.png)

**Comment by tltv** [comment]
Looks like gantt's theme files are not used. Have you compiled Sass to css? Vaadin Sass compiler should do that on the fly if development mode is enabled. But you can compile it also explicitly. See few options how to do it from here: https://vaadin.com/book/-/page/themes.compiling.html

Gantt jar package needs to be also in Sass compiler's classpath. Otherwise required gantt scss file(s) won't be included in theme.

**Comment by kadireray** [comment]
Thank you very much. It works great after I compile theme. I havent look to widgetset.gwt.xml file. There are no inherited .scss file in it. I wonder to know why didnt you use ? Is there anything that I missed?

**Comment by tltv** [comment]
Great to hear it worked. 
Inheriting scss files in gwt.xml does not work like it works with plain css files. Addon Jar is packaged with a Manifest parameter "Vaadin-Stylesheets: VAADIN/addons/gantt/gantt.scss" which does the trick.
