### ISSUE TITLE
setData() on AbstractStep

### ISSUE THREAD

**Issue by slibert** [tltv/gantt#23]
Hello,

It would be nice to have a setData on AbstractStep object. For instance, it would help keeping a link between database object and on-screen step.

Regards

**Comment by tltv** [comment]
See my related comments also in https://github.com/tltv/gantt/issues/24

Using a setData(Object) approach in shared state is problematic as the data need to be serializable by GWT. API can't just allow putting anything there.

Would it make sense to put a optional identifier field into AbstractStep with getter and setter?
That way it would be trivial to keep the link between a AbstractSetp and database object.

Another way would be to use AbstractStepComponent, which is currently only used internally. It's not available via API, but it could be used to store AbstractStep specific data just like with any Vaadin component.
See Gantt.getStepComponent(AbstractStep) private method.

Try to add following methods in Gantt (by extending it, you need to copy private getStepComponent method):

    public void setData(AbstractStep step, Object data) {
        AbstractStepComponent c = getStepComponent(step);
        if (c != null) {
            c.setData(data);
        }
    }

    public Object getData(AbstractStep step) {
        AbstractStepComponent c = getStepComponent(step);
        return (c != null) ? c.getData() : null;
    }

If either or both ways would help, I can consider adding it into addon.

**Comment by tltv** [comment]
Latest version 0.9.1 has now both AbstractStep.identifier and Gantt.setData(AbstractStep,Object)  / getData(AbstractStep).
