### ISSUE TITLE
Gaant-demo integration not working. 

### ISSUE THREAD

**Issue by kernelfreak** [tltv/gantt#25]
Hi, 

I am trying to integrate the gaant-demo into our Spring-MVC application. I am having some problem with Widgetset. Can you kindly help me out. Thanks.

Here is the screenshot, which indicates the gaant-charts are not getting loaded. 

Sorry for the messed up indentation in the code, Github does not seem to support ctrl+k or other shortcuts, and no tab press to indent fast. NICE!!!

PostImage link :  http://s15.postimg.org/70iii7yrv/Screenshot_from_2015_11_18_15_18_18.png

Code : 

       @Theme("demo")
      @SpringUI
      @SuppressWarnings("serial")
       public class MyVaadinUI extends UI {

       @WebServlet(value = "/testvaadin", asyncSupported = true)
      @VaadinServletConfiguration(productionMode = false, ui = MyVaadinUI.class, widgetset =      "org.tltv.gantt.demo.DemoWidgetSet")
        public static class Servlet extends SpringVaadinServlet {
        }

        After this line, I copy pasted the entire contents of DemoUI.java.
         Pastebin  link : http://pastebin.com/mi1ZhH30
        }

POM.xml : 

             <vaadin.version>7.5.7</vaadin.version>

           <parent>
                   <groupId>io.spring.platform</groupId>
                  <artifactId>platform-bom</artifactId>
                <version>1.1.3.RELEASE</version>
                  <relativePath/>
             </parent>

             <repositories>
        <repository>
            <id>vaadin-addons</id>
            <url>http://maven.vaadin.com/vaadin-addons</url>
        </repository>

    </repositories>

    <dependencies>

        
        <dependency>
            <groupId>com.vaadin</groupId>
            <artifactId>vaadin-spring</artifactId>
            <version>1.0.0</version>
        </dependency>

        <dependency>
            <groupId>com.vaadin</groupId>
            <artifactId>vaadin-themes</artifactId>
            <version>${vaadin.version}</version>
        </dependency>

        <dependency>
            <groupId>com.vaadin</groupId>
            <artifactId>vaadin-client-compiled</artifactId>
            <version>${vaadin.version}</version>
        </dependency>

        <dependency>
            <groupId>com.vaadin</groupId>
            <artifactId>vaadin-push</artifactId>
            <version>${vaadin.version}</version>
        </dependency>

        <dependency>
            <groupId>org.tltv.gantt</groupId>
            <artifactId>gantt-addon</artifactId>
            <version>0.9.0</version>
        </dependency>

web.xml : 

             <servlet>
                   <servlet-name>vaadin-spring</servlet-name>
                   <servlet-class>com.vaadin.server.VaadinServlet</servlet-class>
                 <init-param>
                       <description>
                          Vaadin UI class to use</description>
                          <param-name>UI</param-name>
                       <param-value>com.journaldev.spring.Vaadin.MyVaadinUI</param-value>
                       </init-param>
                      <async-supported>true</async-supported>
                      </servlet>

                 <context-param>
                       <param-name>productionMode</param-name>
                         <param-value>false</param-value>
                 </context-param>

               <servlet-mapping>
                     <servlet-name>vaadin-spring</servlet-name>
                    <url-pattern>/*</url-pattern>
                </servlet-mapping>

What's the deal with widgetset that I always have problem with Vaadin and now with this project. I cannot find the files for widgetset and no answers on forums help. I hope you know already. Thanks a lot...

**Comment by tltv** [comment]
I see that MyVaadinUI uses same widgetset name as the Gantt demo uses. gantt jar package does not contain the demo widgetset and that's why it's not actually compiled and your UI can't find that widgetset.

In other words, you need this file in your project: 
https://github.com/tltv/gantt/blob/master/gantt-demo/src/main/resources/org/tltv/gantt/demo/DemoWidgetSet.gwt.xml
In addition, to make the theme work. You need also all scss files in here: 
https://github.com/tltv/gantt/tree/master/gantt-demo/src/main/webapp/VAADIN/themes/demo
Place them in the same path as in the demo, and recompile the widgetset.

**Comment by kernelfreak** [comment]
Hi,

Sorry for the late reply. Thank you for the information. I will try this out. Although I stopped using Vaadin, but just to make sure, so I can properly use it in future. Thank you.
