### ISSUE TITLE
setIdentifier on SubStep - breaks ClickListener

### ISSUE THREAD

**Issue by lrozenblyum** [tltv/gantt#30]
SCENARIO:
For a substep in demo page
subStep1.setIdentifier( 123L );

Click on that substep on screen

EXPECTED:
No issues, just some custom value is available to retrieve from the SubStep

ACTUALLY:
Gantt.ClickListener is called, but event.getStep() is null

java.lang.NullPointerException
	at com.vaadin.data.util.BeanItem.<init>(BeanItem.java:61)
	at org.tltv.gantt.demo.DemoUI.openStepEditor(DemoUI.java:625)

**Comment by tltv** [comment]
Identifier field in hashCode and equals methods in AbstractStep class messed up internal Gantt logic when identifier was actually set.

**Comment by lrozenblyum** [comment]
Thanks for fixing this!
