### ISSUE TITLE
Export to img or pdf

### ISSUE THREAD

**Issue by Picazamora** [tltv/gantt#37]
Hello

There is a possibility to export the graph in pdf or as an image to be printed, is an option that other libraries contemplated.

A greeting.

**Comment by tltv** [comment]
Sorry to disappoint, but a feature to export to image or any other printable format is out of scope with Gantt component. 
Component is not designed to be "printing friendly", but maybe with some third party libraries the whole component could be converted to SVG and then processed further on server to prefered format.
