### ISSUE TITLE
Increase width of gantt grid cells

### ISSUE THREAD

**Issue by dmakis** [tltv/gantt#40]
Hi,

Great add-on!
I need to increase the width of resolution grid cells. I'm using the gantt chart with an hour resolution to represent tasks on a 24 hour time frame and so it would be great to increase the width of each hour cell in order to make the graph more visually pleasant...

![gantt](https://cloud.githubusercontent.com/assets/5311952/14600437/4021948a-0565-11e6-9f9a-0ebc8917c163.jpg)

Many thanks

**Comment by tltv** [comment]
Quick and dirty way is to force some min-width for all .col elements. Add something like .col { min-width: 40px}
That works if you need only day/hour resolution.

I made a fix that allows easier way to change minimum allowed width for grid'c cells.
With this fix you can use for day and hour resultion the following css rule:
`
.col.measure {
  min-width: 40px;
}
`
And for week resoution:
`
.col.w.measure {
  min-width: 70px;
}
`
