### ISSUE TITLE
Problems with appearance after removal layout.

### ISSUE THREAD

**Issue by etkach** [tltv/gantt#46]
I work with a demo. Added to the VerticalLayout components. After removing any changes appear to have been below components my not drawn layer (including Gantt).

P.S. such problem occurs only when the chart displayed Predecessors line

**Comment by tltv** [comment]
Try with version 0.9.4. It has few fixes to bugs that might have caused this kind of behaviour.

**Comment by etkach** [comment]
In version 0.9.4 the same problem

**Comment by tltv** [comment]
Could you please give a simple test code how to reproduce this issue. Thanks.
