### ISSUE TITLE
Detect Right Mouse Click in Clickevent

### ISSUE THREAD

**Issue by d2k2-git** [tltv/gantt#49]
Would be nice to detect which mousebutton was clicked in the Clickevent so we can implement for example a contextmenu for step editing.

**Comment by tltv** [comment]
Added MouseEventDetails to ClickEvent. MouseEventDetails is part of Vaadin framework and you get it with `ClickEvent.getMouseEventDetails()`.

Use it to detect right click like this:
```
gantt.addClickListener(new Gantt.ClickListener() {
            public void onGanttClick(org.tltv.gantt.Gantt.ClickEvent event) {
                if (MouseButton.RIGHT.equals(event.getDetails().getButton())) {
                    // do something
                }
            }
        });
}
```
Also notice new variable `GanttState.defaultContextMenuEnabled`. This is false by default and it means simply that the default context menu is disabled by default completely. Enable with `Gantt.setDefaultContextMenuEnabled(true)` if needed.
