### ISSUE TITLE
Drag and drop steps between lines

### ISSUE THREAD

**Issue by tistvan** [tltv/gantt#50]
Hello,

I am building a resource planning app in which the steps are tasks and the lines are people (or other resources). But with this addon the user is not able to drag a step (task) from one line (person) to another.
Are you planning to add this functionality? Or ability to drag a substep from one parent to another? Or do you have any suggestion how can I implement this with the existing features?

Thanks

**Comment by tltv** [comment]
I don't have plans to add new features atm. But this feature is partially supported already. 
You can override `Gantt.fireMoveEvent(String stepUid, String newStepUid, long startDate, long endDate)` method where newStepUid points to the drop target. This information is not used anywhere, but it's there and might be useful.

**Comment by tistvan** [comment]
Overriding Gantt.fireMoveEvent wasn't enough because I had to visualize the movement so I implemented it and created a pull request.

**Comment by tltv** [comment]
Thanks for the pull request tisvan. 
Its merged in and as this version did not keep server and client side step order in sync based on shared state's steps list, and as it was basically not even possible before, I've made several changed to keep that list in sync.
This results to slighly different ux when all steps are actually re-postioned and empty rows are removed after each move.

Feature is disabled by default and can be enabled with `Gantt.setMovableStepsBetweenRows(true)`.

**Comment by tistvan** [comment]
Thanks for merging and refactoring my changes. This feature is much better now.

With my original implementation it was possible to move two or more steps to a row. I know this is (more or less) out of the scope of this addon but I need this functionality.
Can you suggest me a sollution? Should I bring lineIndex (rowIndex) variable back and create a new boolean in Gantt.java for this feature? Or should I implement it in another way? Or should this feature exist only in my fork?

**Comment by tltv** [comment]
I would suggest to use sub steps. Now with the latest changes today, sub-steps are movable between steps too. Try it with the demo app and see how it works. 
I guess that you would need to do some extra server side logic on each move to actually remove steps without any sub-steps, but that can be done in move listener without extending or overriding anything.

**Comment by tistvan** [comment]
Wow! Awesome! Thanks :)

**Comment by tistvan** [comment]
I added this updated Gantt to our project and now it is perfect. The only difference was that the user was able to drag complete rows (parent steps). So I implemented a feature to disable movement in step level. I created a pull request: https://github.com/tltv/gantt/pull/62

Thanks again
