### ISSUE TITLE
Undefined height vs add step

### ISSUE THREAD

**Issue by tistvan** [tltv/gantt#55]
When the gantt's height is undefined and I add a step to the gantt from a listener, the component doesn't grow. You can reproduce the bug by commenting out gantt.setHeight(500, Unit.PIXELS); line in DemoUI and add adding a step from the menu.
Can you suggest me a workaround for this issue (if exists)? Can I force height update somehow?

Thanks

**Comment by tistvan** [comment]
If I comment out the following lines in GantWidget.notifyHeightChanged the bug disappears:

```java
container.getStyle().setHeight(
                    height - getTimelineHeight()
                            - getHorizontalScrollbarSpacerHeight(), Unit.PX);
```

**Comment by tltv** [comment]
Pull request merged. Seems to work. Thanks for the patch tistvan!
