### ISSUE TITLE
Vaadin 8 official support

### ISSUE THREAD

**Issue by lrozenblyum** [tltv/gantt#63]
It would be nice to add support of Vaadin8 to the Gantt addon

https://vaadin.com/blog/-/blogs/vaadin-framework-8-is-out
https://vaadin.com/framework/whatsnew

**Comment by tltv** [comment]
Version 1.0.0 is Vaadin 8 compatible and released today.

**Comment by lrozenblyum** [comment]
Thanks @tltv !
