### ISSUE TITLE
vaadin-compatibility dependencies

### ISSUE THREAD

**Issue by tistvan** [tltv/gantt#64]
Hello,

Are you planning to remove vaadin-compatibility dependencies from the addon?
I am planning to upgrade my project to Vaadin 8 (actually to 8.1) and I don't want to use vaadin-compatibility package. But if I add this addon to my project vaadin-compatibility jars will be there as transitive dependencies.

Thanks,
István

**Comment by tistvan** [comment]
It's actually quite easy. But you have to drop Table and TreeTable support. I created a build for myself and it works after I commented out these features. See this commit for details: https://github.com/tistvan/gantt/commit/f59c58bdaa9c2556714f7ce02b424509cb7a5995
(I don't want to make a pull request from it because it's not the proper solution and I don't want to be the person who drops Table and TreeTable support.)

**Comment by tltv** [comment]
Thanks tistvan.
v7 compatibility dependencies will be removed in future versions. 1.0.1 will most likely be the last version still including those dependencies.

**Comment by tltv** [comment]
v1.0.3 drops Table support along V7 compatibility dependencies.
