### ISSUE TITLE
Problem with customized bar height in vaadin 8

### ISSUE THREAD

**Issue by yya109** [tltv/gantt#67]
In vaadin 7, we can use CSS to customize the bar height of a gantt diagram like:
Java: gantt.addStyle(“test-style”);
CSS: .test-style {
                      .bar{
                            height: 40px;
                            }
                }
and this works fine.

After migration in vaadin8, the rendering of the background-SVG(GanttWidget#bgGrid) doesn't work correctly and the height of SVG is incorrect. After debugging, we found out that the method GanttWidget#addStep still used the default bar height defined in gantt-valo.scss during the first invocation (triggered by GanttConnector#onConnectorHierarchyChange). Therefore, the calculation of GanttWidget#contentHeight do not match the customized bar height. And the GanttWidget#bgGrid will be generated and use the incorrect GanttWidget#contentHeight for height-property. After refreshing, the steps will be aligned with the correct styles, but the background SVG remains incorrect, because the GanttWidget#bgGrid will be only generated once.

We assume, that vaadin8 changed the mechanism to apply customized Stylesheet. At the beginning of the page generation, only default Stylesheet is used. We don't have any chance to update the bg-SVG after the applying of customized bar height. 

Can you check it please? Thanks!

**Comment by socialdinner** [comment]
We have the same Problem. Could you please fix that? I already postet this to the Vaadin Forum Add-On Section with sample code and screenshots.
Thanks Dennis

**Comment by tltv** [comment]
Fixed in master branch.
