### ISSUE TITLE
Make addStyleName and removeStyleName available for AbstractStep

### ISSUE THREAD

**Issue by StephanPirnbaum** [tltv/gantt#69]
Once added to the Gantt chart, it is not possible to change the color/style of a Step since the StepComponent is not notified when `setBackgroundColor`/`setStyleName` is called. As there is no way to retrieve the StepComponent for a Step from the Gantt chart, a workaround using `removeStep` and `addStep` must be implemented. It would be great if the changes to the style of a Step would be propagated to the StepComponent

**Comment by tltv** [comment]
Gantt.markStepDirty(AbstractStep) notifies StepComponent to repaint.

**Comment by StephanPirnbaum** [comment]
When does it take effect? I replaced my workaround with the solution you suggested, but nothing happens.

**Comment by tltv** [comment]
Once step is marked dirty with markStepDirty, any changes to Step, including background color and style will be handled on next response to the browser via StepConnector/SubStepConnector.

There seems to be a bug in stylename change handling. Old style name is not cleared properly. Every change will just insert a new style name.

**Comment by tltv** [comment]
FIxed in master
