### ISSUE TITLE
Removing style names from steps does not work

### ISSUE THREAD

**Issue by Wnt** [tltv/gantt#74]
I have a click listener where I toggle a `selected` class name like so:
```java
(Gantt.ClickEvent e) -> {
  AbstractStep step = e.getStep();
  String styleName = step.getStyleName();
  if (styleName.contains("selected")) {
    styleName = styleName.replace("selected", "").trim();
    step.setStyleName(styleName);
    selected.remove(dtRow);
  } else {
    step.setStyleName(styleName + " selected");
    selected.add(dtRow);
  }
}
```
but on the second click the class name `selected` is not removed from the step from the client-side element. On the server side the styleName is as expected.

Looks like `AbstractStepWidget.extraStyle` remains always empty, so style names are never removed on the client-side from the element.
Problematic code: is in `AbstractStepWidget.updateStyle()`
https://github.com/tltv/gantt/blob/4e80e582e00cecabe61b64bfebd980582ab80794/gantt-addon/src/main/java/org/tltv/gantt/client/AbstractStepWidget.java#L98

**Comment by tltv** [comment]
Sounds like same issue that was fixed to master in January (https://github.com/tltv/gantt/issues/69). 
Did you try it with master branch?
If you did then this is regression from that fix.
