### ISSUE TITLE
Multiple Steps on the Same Row

### ISSUE THREAD

**Issue by iajones** [tltv/gantt#8]
Hi,

Is there any way to add multiple steps on the same row - similar to the way you can split a task in MS Project?

Many thanks,

Ian

**Comment by hendryt** [comment]
Hi

Will Splitting be supported in the near future?

Hendry

**Comment by tltv** [comment]
I believe it will. Showing relationships between steps will be the next new feature. Splitting comes after that.

**Comment by hendryt** [comment]
Thanks, but unfortunately that does not sound like it will be soon enough. I need this functionality within the next 2 weeks.
I might need to look for an alternate solution.

**Comment by socialdinner** [comment]
Hi Tomi,
I really like your Gantt, but I also need to have more steps in the same row. It is the only thing I miss. I would appreciate it so much, if this will follow in the near future. 
Thanks a lot Dennis

**Comment by hendryt** [comment]
Any possible ETA on the splitting?

**Comment by socialdinner** [comment]
SubSteps are already available in the source files. I downloaded them and it works good. The only thing I miss is an updated .jar file on the vaadin page. Thanks!

**Comment by tltv** [comment]
Sub-steps are now available in version 0.9.0.
